<event logger="KPIWeb.LogWriter" timestamp="2015-02-22T11:18:20.0626255+03:00" level="ERROR" thread="12" domain="/LM/W3SVC/6/ROOT-1-130690666551180548" username="HP_ProBook_4340\SiV@S"><message>System.Threading.ThreadAbortException: Поток находился в процессе прерывания.    в System.Threading.Thread.AbortInternal()    в System.Threading.Thread.Abort(Object stateInfo)    в System.Web.HttpResponse.AbortCurrentThread()    в System.Web.HttpResponse.End()    в System.Web.HttpResponse.Redirect(String url, Boolean endResponse, Boolean permanent)    в System.Web.HttpResponse.Redirect(String url)    в KPIWeb.Account.Login.LogIn(Object sender, EventArgs e) в c:\Users\SiV@S\Desktop\Repo\Projects.git\trunk\KPIproduction\KPIWeb\KPIWeb\Account\Login.aspx.cs:строка 54KPIWeb.LogWriter  Void WriteError(System.Exception) Line Number: 0</message><properties><data name="log4net:HostName" value="HP_ProBook_4340" /></properties></event>
<event logger="KPIWeb.LogWriter" timestamp="2015-02-22T11:20:51.0052589+03:00" level="ERROR" thread="9" domain="/LM/W3SVC/6/ROOT-1-130690668300730616" username="HP_ProBook_4340\SiV@S"><message>System.Threading.ThreadAbortException: Поток находился в процессе прерывания.    в System.Threading.Thread.AbortInternal()    в System.Threading.Thread.Abort(Object stateInfo)    в System.Web.HttpResponse.AbortCurrentThread()    в System.Web.HttpResponse.End()    в System.Web.HttpResponse.Redirect(String url, Boolean endResponse, Boolean permanent)    в System.Web.HttpResponse.Redirect(String url)    в KPIWeb.Account.Login.LogIn(Object sender, EventArgs e) в c:\Users\SiV@S\Desktop\Repo\Projects.git\trunk\KPIproduction\KPIWeb\KPIWeb\Account\Login.aspx.cs:строка 54KPIWeb.LogWriter  Void WriteError(System.Exception) Line Number: 0</message><properties><data name="log4net:HostName" value="HP_ProBook_4340" /></properties></event>
<event logger="KPIWeb.LogWriter" timestamp="2015-02-22T11:23:10.6392455+03:00" level="ERROR" thread="8" domain="/LM/W3SVC/6/ROOT-1-130690669490358659" username="HP_ProBook_4340\SiV@S"><message>System.Threading.ThreadAbortException: Поток находился в процессе прерывания.    в System.Threading.Thread.AbortInternal()    в System.Threading.Thread.Abort(Object stateInfo)    в System.Web.HttpResponse.AbortCurrentThread()    в System.Web.HttpResponse.End()    в System.Web.HttpResponse.Redirect(String url, Boolean endResponse, Boolean permanent)    в System.Web.HttpResponse.Redirect(String url)    в KPIWeb.Account.Login.LogIn(Object sender, EventArgs e) в c:\Users\SiV@S\Desktop\Repo\Projects.git\trunk\KPIproduction\KPIWeb\KPIWeb\Account\Login.aspx.cs:строка 54KPIWeb.LogWriter  Void WriteError(System.Exception) Line Number: 0</message><properties><data name="log4net:HostName" value="HP_ProBook_4340" /></properties></event>
<event logger="KPIWeb.LogWriter" timestamp="2015-02-22T11:27:57.0386266+03:00" level="ERROR" thread="19" domain="/LM/W3SVC/6/ROOT-1-130690671050777910" username="HP_ProBook_4340\SiV@S"><message>System.Threading.ThreadAbortException: Поток находился в процессе прерывания.    в System.Threading.Thread.AbortInternal()    в System.Threading.Thread.Abort(Object stateInfo)    в System.Web.HttpResponse.AbortCurrentThread()    в System.Web.HttpResponse.End()    в System.Web.HttpResponse.Redirect(String url, Boolean endResponse, Boolean permanent)    в System.Web.HttpResponse.Redirect(String url)    в KPIWeb.Account.Login.LogIn(Object sender, EventArgs e) в c:\Users\SiV@S\Desktop\Repo\Projects.git\trunk\KPIproduction\KPIWeb\KPIWeb\Account\Login.aspx.cs:строка 54KPIWeb.LogWriter  Void WriteError(System.Exception) Line Number: 0</message><properties><data name="log4net:HostName" value="HP_ProBook_4340" /></properties></event>
<event logger="KPIWeb.LogWriter" timestamp="2015-02-22T11:29:52.8642515+03:00" level="ERROR" thread="7" domain="/LM/W3SVC/6/ROOT-1-130690673726100930" username="HP_ProBook_4340\SiV@S"><message>System.Threading.ThreadAbortException: Поток находился в процессе прерывания.    в System.Threading.Thread.AbortInternal()    в System.Threading.Thread.Abort(Object stateInfo)    в System.Web.HttpResponse.AbortCurrentThread()    в System.Web.HttpResponse.End()    в System.Web.HttpResponse.Redirect(String url, Boolean endResponse, Boolean permanent)    в System.Web.HttpResponse.Redirect(String url)    в KPIWeb.Account.Login.LogIn(Object sender, EventArgs e) в c:\Users\SiV@S\Desktop\Repo\Projects.git\trunk\KPIproduction\KPIWeb\KPIWeb\Account\Login.aspx.cs:строка 54KPIWeb.LogWriter  Void WriteError(System.Exception) Line Number: 0</message><properties><data name="log4net:HostName" value="HP_ProBook_4340" /></properties></event>
<event logger="KPIWeb.LogWriter" timestamp="2015-02-22T11:32:33.6454476+03:00" level="ERROR" thread="7" domain="/LM/W3SVC/6/ROOT-1-130690674913318835" username="HP_ProBook_4340\SiV@S"><message>System.Threading.ThreadAbortException: Поток находился в процессе прерывания.    в System.Threading.Thread.AbortInternal()    в System.Threading.Thread.Abort(Object stateInfo)    в System.Web.HttpResponse.AbortCurrentThread()    в System.Web.HttpResponse.End()    в System.Web.HttpResponse.Redirect(String url, Boolean endResponse, Boolean permanent)    в System.Web.HttpResponse.Redirect(String url)    в KPIWeb.Account.Login.LogIn(Object sender, EventArgs e) в c:\Users\SiV@S\Desktop\Repo\Projects.git\trunk\KPIproduction\KPIWeb\KPIWeb\Account\Login.aspx.cs:строка 54KPIWeb.LogWriter  Void WriteError(System.Exception) Line Number: 0</message><properties><data name="log4net:HostName" value="HP_ProBook_4340" /></properties></event>
<event logger="KPIWeb.LogWriter" timestamp="2015-02-22T11:35:39.7310911+03:00" level="ERROR" thread="9" domain="/LM/W3SVC/6/ROOT-1-130690677065221917" username="HP_ProBook_4340\SiV@S"><message>System.Threading.ThreadAbortException: Поток находился в процессе прерывания.    в System.Threading.Thread.AbortInternal()    в System.Threading.Thread.Abort(Object stateInfo)    в System.Web.HttpResponse.AbortCurrentThread()    в System.Web.HttpResponse.End()    в System.Web.HttpResponse.Redirect(String url, Boolean endResponse, Boolean permanent)    в System.Web.HttpResponse.Redirect(String url)    в KPIWeb.Account.Login.LogIn(Object sender, EventArgs e) в c:\Users\SiV@S\Desktop\Repo\Projects.git\trunk\KPIproduction\KPIWeb\KPIWeb\Account\Login.aspx.cs:строка 54KPIWeb.LogWriter  Void WriteError(System.Exception) Line Number: 0</message><properties><data name="log4net:HostName" value="HP_ProBook_4340" /></properties></event>
<event logger="KPIWeb.LogWriter" timestamp="2015-02-22T11:37:59.5840902+03:00" level="ERROR" thread="7" domain="/LM/W3SVC/6/ROOT-1-130690678455641444" username="HP_ProBook_4340\SiV@S"><message>System.Threading.ThreadAbortException: Поток находился в процессе прерывания.    в System.Threading.Thread.AbortInternal()    в System.Threading.Thread.Abort(Object stateInfo)    в System.Web.HttpResponse.AbortCurrentThread()    в System.Web.HttpResponse.End()    в System.Web.HttpResponse.Redirect(String url, Boolean endResponse, Boolean permanent)    в System.Web.HttpResponse.Redirect(String url)    в KPIWeb.Account.Login.LogIn(Object sender, EventArgs e) в c:\Users\SiV@S\Desktop\Repo\Projects.git\trunk\KPIproduction\KPIWeb\KPIWeb\Account\Login.aspx.cs:строка 54KPIWeb.LogWriter  Void WriteError(System.Exception) Line Number: 0</message><properties><data name="log4net:HostName" value="HP_ProBook_4340" /></properties></event>
<event logger="KPIWeb.LogWriter" timestamp="2015-02-22T11:39:07.3729675+03:00" level="ERROR" thread="11" domain="/LM/W3SVC/6/ROOT-1-130690679215024878" username="HP_ProBook_4340\SiV@S"><message>System.Threading.ThreadAbortException: Поток находился в процессе прерывания.    в System.Threading.Thread.AbortInternal()    в System.Threading.Thread.Abort(Object stateInfo)    в System.Web.HttpResponse.AbortCurrentThread()    в System.Web.HttpResponse.End()    в System.Web.HttpResponse.Redirect(String url, Boolean endResponse, Boolean permanent)    в System.Web.HttpResponse.Redirect(String url)    в KPIWeb.Account.Login.LogIn(Object sender, EventArgs e) в c:\Users\SiV@S\Desktop\Repo\Projects.git\trunk\KPIproduction\KPIWeb\KPIWeb\Account\Login.aspx.cs:строка 54KPIWeb.LogWriter  Void WriteError(System.Exception) Line Number: 0</message><properties><data name="log4net:HostName" value="HP_ProBook_4340" /></properties></event>
<event logger="KPIWeb.LogWriter" timestamp="2015-02-22T11:40:40.9853219+03:00" level="ERROR" thread="7" domain="/LM/W3SVC/6/ROOT-1-130690680128097103" username="HP_ProBook_4340\SiV@S"><message>System.Threading.ThreadAbortException: Поток находился в процессе прерывания.    в System.Threading.Thread.AbortInternal()    в System.Threading.Thread.Abort(Object stateInfo)    в System.Web.HttpResponse.AbortCurrentThread()    в System.Web.HttpResponse.End()    в System.Web.HttpResponse.Redirect(String url, Boolean endResponse, Boolean permanent)    в System.Web.HttpResponse.Redirect(String url)    в KPIWeb.Account.Login.LogIn(Object sender, EventArgs e) в c:\Users\SiV@S\Desktop\Repo\Projects.git\trunk\KPIproduction\KPIWeb\KPIWeb\Account\Login.aspx.cs:строка 54KPIWeb.LogWriter  Void WriteError(System.Exception) Line Number: 0</message><properties><data name="log4net:HostName" value="HP_ProBook_4340" /></properties></event>
<event logger="KPIWeb.LogWriter" timestamp="2015-02-22T11:43:12.1919704+03:00" level="ERROR" thread="9" domain="/LM/W3SVC/6/ROOT-1-130690681677075700" username="HP_ProBook_4340\SiV@S"><message>System.Threading.ThreadAbortException: Поток находился в процессе прерывания.    в System.Threading.Thread.AbortInternal()    в System.Threading.Thread.Abort(Object stateInfo)    в System.Web.HttpResponse.AbortCurrentThread()    в System.Web.HttpResponse.End()    в System.Web.HttpResponse.Redirect(String url, Boolean endResponse, Boolean permanent)    в System.Web.HttpResponse.Redirect(String url)    в KPIWeb.Account.Login.LogIn(Object sender, EventArgs e) в c:\Users\SiV@S\Desktop\Repo\Projects.git\trunk\KPIproduction\KPIWeb\KPIWeb\Account\Login.aspx.cs:строка 54KPIWeb.LogWriter  Void WriteError(System.Exception) Line Number: 0</message><properties><data name="log4net:HostName" value="HP_ProBook_4340" /></properties></event>
<event logger="KPIWeb.LogWriter" timestamp="2015-02-22T11:44:33.710633+03:00" level="ERROR" thread="10" domain="/LM/W3SVC/6/ROOT-1-130690682497742639" username="HP_ProBook_4340\SiV@S"><message>System.Threading.ThreadAbortException: Поток находился в процессе прерывания.    в System.Threading.Thread.AbortInternal()    в System.Threading.Thread.Abort(Object stateInfo)    в System.Web.HttpResponse.AbortCurrentThread()    в System.Web.HttpResponse.End()    в System.Web.HttpResponse.Redirect(String url, Boolean endResponse, Boolean permanent)    в System.Web.HttpResponse.Redirect(String url)    в KPIWeb.Account.Login.LogIn(Object sender, EventArgs e) в c:\Users\SiV@S\Desktop\Repo\Projects.git\trunk\KPIproduction\KPIWeb\KPIWeb\Account\Login.aspx.cs:строка 54KPIWeb.LogWriter  Void WriteError(System.Exception) Line Number: 0</message><properties><data name="log4net:HostName" value="HP_ProBook_4340" /></properties></event>
<event logger="KPIWeb.LogWriter" timestamp="2015-02-22T11:47:59.2703903+03:00" level="ERROR" thread="10" domain="/LM/W3SVC/6/ROOT-1-130690684485976359" username="HP_ProBook_4340\SiV@S"><message>System.Threading.ThreadAbortException: Поток находился в процессе прерывания.    в System.Threading.Thread.AbortInternal()    в System.Threading.Thread.Abort(Object stateInfo)    в System.Web.HttpResponse.AbortCurrentThread()    в System.Web.HttpResponse.End()    в System.Web.HttpResponse.Redirect(String url, Boolean endResponse, Boolean permanent)    в System.Web.HttpResponse.Redirect(String url)    в KPIWeb.Account.Login.LogIn(Object sender, EventArgs e) в c:\Users\SiV@S\Desktop\Repo\Projects.git\trunk\KPIproduction\KPIWeb\KPIWeb\Account\Login.aspx.cs:строка 54KPIWeb.LogWriter  Void WriteError(System.Exception) Line Number: 0</message><properties><data name="log4net:HostName" value="HP_ProBook_4340" /></properties></event>
<event logger="KPIWeb.LogWriter" timestamp="2015-02-22T11:49:34.5198383+03:00" level="ERROR" thread="12" domain="/LM/W3SVC/6/ROOT-1-130690685359486321" username="HP_ProBook_4340\SiV@S"><message>System.Threading.ThreadAbortException: Поток находился в процессе прерывания.    в System.Threading.Thread.AbortInternal()    в System.Threading.Thread.Abort(Object stateInfo)    в System.Web.HttpResponse.AbortCurrentThread()    в System.Web.HttpResponse.End()    в System.Web.HttpResponse.Redirect(String url, Boolean endResponse, Boolean permanent)    в System.Web.HttpResponse.Redirect(String url)    в KPIWeb.Account.Login.LogIn(Object sender, EventArgs e) в c:\Users\SiV@S\Desktop\Repo\Projects.git\trunk\KPIproduction\KPIWeb\KPIWeb\Account\Login.aspx.cs:строка 54KPIWeb.LogWriter  Void WriteError(System.Exception) Line Number: 0</message><properties><data name="log4net:HostName" value="HP_ProBook_4340" /></properties></event>
<event logger="KPIWeb.LogWriter" timestamp="2015-02-22T11:51:39.1609674+03:00" level="ERROR" thread="8" domain="/LM/W3SVC/6/ROOT-1-130690686690972478" username="HP_ProBook_4340\SiV@S"><message>System.Threading.ThreadAbortException: Поток находился в процессе прерывания.    в System.Threading.Thread.AbortInternal()    в System.Threading.Thread.Abort(Object stateInfo)    в System.Web.HttpResponse.AbortCurrentThread()    в System.Web.HttpResponse.End()    в System.Web.HttpResponse.Redirect(String url, Boolean endResponse, Boolean permanent)    в System.Web.HttpResponse.Redirect(String url)    в KPIWeb.Account.Login.LogIn(Object sender, EventArgs e) в c:\Users\SiV@S\Desktop\Repo\Projects.git\trunk\KPIproduction\KPIWeb\KPIWeb\Account\Login.aspx.cs:строка 54KPIWeb.LogWriter  Void WriteError(System.Exception) Line Number: 0</message><properties><data name="log4net:HostName" value="HP_ProBook_4340" /></properties></event>
<event logger="KPIWeb.LogWriter" timestamp="2015-02-22T11:52:31.8049784+03:00" level="ERROR" thread="10" domain="/LM/W3SVC/6/ROOT-1-130690687258224923" username="HP_ProBook_4340\SiV@S"><message>System.Threading.ThreadAbortException: Поток находился в процессе прерывания.    в System.Threading.Thread.AbortInternal()    в System.Threading.Thread.Abort(Object stateInfo)    в System.Web.HttpResponse.AbortCurrentThread()    в System.Web.HttpResponse.End()    в System.Web.HttpResponse.Redirect(String url, Boolean endResponse, Boolean permanent)    в System.Web.HttpResponse.Redirect(String url)    в KPIWeb.Account.Login.LogIn(Object sender, EventArgs e) в c:\Users\SiV@S\Desktop\Repo\Projects.git\trunk\KPIproduction\KPIWeb\KPIWeb\Account\Login.aspx.cs:строка 54KPIWeb.LogWriter  Void WriteError(System.Exception) Line Number: 0</message><properties><data name="log4net:HostName" value="HP_ProBook_4340" /></properties></event>
<event logger="KPIWeb.LogWriter" timestamp="2015-02-22T11:55:37.4165948+03:00" level="ERROR" thread="7" domain="/LM/W3SVC/6/ROOT-1-130690688981593494" username="HP_ProBook_4340\SiV@S"><message>System.Threading.ThreadAbortException: Поток находился в процессе прерывания.    в System.Threading.Thread.AbortInternal()    в System.Threading.Thread.Abort(Object stateInfo)    в System.Web.HttpResponse.AbortCurrentThread()    в System.Web.HttpResponse.End()    в System.Web.HttpResponse.Redirect(String url, Boolean endResponse, Boolean permanent)    в System.Web.HttpResponse.Redirect(String url)    в KPIWeb.Account.Login.LogIn(Object sender, EventArgs e) в c:\Users\SiV@S\Desktop\Repo\Projects.git\trunk\KPIproduction\KPIWeb\KPIWeb\Account\Login.aspx.cs:строка 54KPIWeb.LogWriter  Void WriteError(System.Exception) Line Number: 0</message><properties><data name="log4net:HostName" value="HP_ProBook_4340" /></properties></event>
<event logger="KPIWeb.LogWriter" timestamp="2015-02-22T11:56:39.7581605+03:00" level="ERROR" thread="8" domain="/LM/W3SVC/6/ROOT-1-130690689747257288" username="HP_ProBook_4340\SiV@S"><message>System.Threading.ThreadAbortException: Поток находился в процессе прерывания.    в System.Threading.Thread.AbortInternal()    в System.Threading.Thread.Abort(Object stateInfo)    в System.Web.HttpResponse.AbortCurrentThread()    в System.Web.HttpResponse.End()    в System.Web.HttpResponse.Redirect(String url, Boolean endResponse, Boolean permanent)    в System.Web.HttpResponse.Redirect(String url)    в KPIWeb.Account.Login.LogIn(Object sender, EventArgs e) в c:\Users\SiV@S\Desktop\Repo\Projects.git\trunk\KPIproduction\KPIWeb\KPIWeb\Account\Login.aspx.cs:строка 54KPIWeb.LogWriter  Void WriteError(System.Exception) Line Number: 0</message><properties><data name="log4net:HostName" value="HP_ProBook_4340" /></properties></event>
<event logger="KPIWeb.LogWriter" timestamp="2015-02-22T11:57:36.5034062+03:00" level="ERROR" thread="8" domain="/LM/W3SVC/6/ROOT-1-130690690322280177" username="HP_ProBook_4340\SiV@S"><message>System.Threading.ThreadAbortException: Поток находился в процессе прерывания.    в System.Threading.Thread.AbortInternal()    в System.Threading.Thread.Abort(Object stateInfo)    в System.Web.HttpResponse.AbortCurrentThread()    в System.Web.HttpResponse.End()    в System.Web.HttpResponse.Redirect(String url, Boolean endResponse, Boolean permanent)    в System.Web.HttpResponse.Redirect(String url)    в KPIWeb.Account.Login.LogIn(Object sender, EventArgs e) в c:\Users\SiV@S\Desktop\Repo\Projects.git\trunk\KPIproduction\KPIWeb\KPIWeb\Account\Login.aspx.cs:строка 54KPIWeb.LogWriter  Void WriteError(System.Exception) Line Number: 0</message><properties><data name="log4net:HostName" value="HP_ProBook_4340" /></properties></event>
<event logger="KPIWeb.LogWriter" timestamp="2015-02-22T11:58:45.0113246+03:00" level="ERROR" thread="8" domain="/LM/W3SVC/6/ROOT-1-130690691011499598" username="HP_ProBook_4340\SiV@S"><message>System.Threading.ThreadAbortException: Поток находился в процессе прерывания.    в System.Threading.Thread.AbortInternal()    в System.Threading.Thread.Abort(Object stateInfo)    в System.Web.HttpResponse.AbortCurrentThread()    в System.Web.HttpResponse.End()    в System.Web.HttpResponse.Redirect(String url, Boolean endResponse, Boolean permanent)    в System.Web.HttpResponse.Redirect(String url)    в KPIWeb.Account.Login.LogIn(Object sender, EventArgs e) в c:\Users\SiV@S\Desktop\Repo\Projects.git\trunk\KPIproduction\KPIWeb\KPIWeb\Account\Login.aspx.cs:строка 54KPIWeb.LogWriter  Void WriteError(System.Exception) Line Number: 0</message><properties><data name="log4net:HostName" value="HP_ProBook_4340" /></properties></event>
<event logger="KPIWeb.LogWriter" timestamp="2015-02-22T11:59:31.9940119+03:00" level="ERROR" thread="10" domain="/LM/W3SVC/6/ROOT-1-130690691490096972" username="HP_ProBook_4340\SiV@S"><message>System.Threading.ThreadAbortException: Поток находился в процессе прерывания.    в System.Threading.Thread.AbortInternal()    в System.Threading.Thread.Abort(Object stateInfo)    в System.Web.HttpResponse.AbortCurrentThread()    в System.Web.HttpResponse.End()    в System.Web.HttpResponse.Redirect(String url, Boolean endResponse, Boolean permanent)    в System.Web.HttpResponse.Redirect(String url)    в KPIWeb.Account.Login.LogIn(Object sender, EventArgs e) в c:\Users\SiV@S\Desktop\Repo\Projects.git\trunk\KPIproduction\KPIWeb\KPIWeb\Account\Login.aspx.cs:строка 54KPIWeb.LogWriter  Void WriteError(System.Exception) Line Number: 0</message><properties><data name="log4net:HostName" value="HP_ProBook_4340" /></properties></event>
<event logger="KPIWeb.LogWriter" timestamp="2015-02-22T12:01:32.5949098+03:00" level="ERROR" thread="11" domain="/LM/W3SVC/6/ROOT-1-130690692643142923" username="HP_ProBook_4340\SiV@S"><message>System.Threading.ThreadAbortException: Поток находился в процессе прерывания.    в System.Threading.Thread.AbortInternal()    в System.Threading.Thread.Abort(Object stateInfo)    в System.Web.HttpResponse.AbortCurrentThread()    в System.Web.HttpResponse.End()    в System.Web.HttpResponse.Redirect(String url, Boolean endResponse, Boolean permanent)    в System.Web.HttpResponse.Redirect(String url)    в KPIWeb.Account.Login.LogIn(Object sender, EventArgs e) в c:\Users\SiV@S\Desktop\Repo\Projects.git\trunk\KPIproduction\KPIWeb\KPIWeb\Account\Login.aspx.cs:строка 54KPIWeb.LogWriter  Void WriteError(System.Exception) Line Number: 0</message><properties><data name="log4net:HostName" value="HP_ProBook_4340" /></properties></event>
<event logger="KPIWeb.LogWriter" timestamp="2015-02-22T12:02:26.1419725+03:00" level="ERROR" thread="8" domain="/LM/W3SVC/6/ROOT-1-130690693206645153" username="HP_ProBook_4340\SiV@S"><message>System.Threading.ThreadAbortException: Поток находился в процессе прерывания.    в System.Threading.Thread.AbortInternal()    в System.Threading.Thread.Abort(Object stateInfo)    в System.Web.HttpResponse.AbortCurrentThread()    в System.Web.HttpResponse.End()    в System.Web.HttpResponse.Redirect(String url, Boolean endResponse, Boolean permanent)    в System.Web.HttpResponse.Redirect(String url)    в KPIWeb.Account.Login.LogIn(Object sender, EventArgs e) в c:\Users\SiV@S\Desktop\Repo\Projects.git\trunk\KPIproduction\KPIWeb\KPIWeb\Account\Login.aspx.cs:строка 54KPIWeb.LogWriter  Void WriteError(System.Exception) Line Number: 0</message><properties><data name="log4net:HostName" value="HP_ProBook_4340" /></properties></event>
<event logger="KPIWeb.LogWriter" timestamp="2015-02-22T12:05:55.5269487+03:00" level="ERROR" thread="12" domain="/LM/W3SVC/6/ROOT-1-130690694922543297" username="HP_ProBook_4340\SiV@S"><message>System.Threading.ThreadAbortException: Поток находился в процессе прерывания.    в System.Threading.Thread.AbortInternal()    в System.Threading.Thread.Abort(Object stateInfo)    в System.Web.HttpResponse.AbortCurrentThread()    в System.Web.HttpResponse.End()    в System.Web.HttpResponse.Redirect(String url, Boolean endResponse, Boolean permanent)    в System.Web.HttpResponse.Redirect(String url)    в KPIWeb.Account.Login.LogIn(Object sender, EventArgs e) в c:\Users\SiV@S\Desktop\Repo\Projects.git\trunk\KPIproduction\KPIWeb\KPIWeb\Account\Login.aspx.cs:строка 54KPIWeb.LogWriter  Void WriteError(System.Exception) Line Number: 0</message><properties><data name="log4net:HostName" value="HP_ProBook_4340" /></properties></event>
<event logger="KPIWeb.LogWriter" timestamp="2015-02-22T12:09:13.2082554+03:00" level="ERROR" thread="9" domain="/LM/W3SVC/6/ROOT-1-130690697300499308" username="HP_ProBook_4340\SiV@S"><message>System.Threading.ThreadAbortException: Поток находился в процессе прерывания.    в System.Threading.Thread.AbortInternal()    в System.Threading.Thread.Abort(Object stateInfo)    в System.Web.HttpResponse.AbortCurrentThread()    в System.Web.HttpResponse.End()    в System.Web.HttpResponse.Redirect(String url, Boolean endResponse, Boolean permanent)    в System.Web.HttpResponse.Redirect(String url)    в KPIWeb.Account.Login.LogIn(Object sender, EventArgs e) в c:\Users\SiV@S\Desktop\Repo\Projects.git\trunk\KPIproduction\KPIWeb\KPIWeb\Account\Login.aspx.cs:строка 54KPIWeb.LogWriter  Void WriteError(System.Exception) Line Number: 0</message><properties><data name="log4net:HostName" value="HP_ProBook_4340" /></properties></event>
<event logger="KPIWeb.LogWriter" timestamp="2015-02-22T12:11:29.0960277+03:00" level="ERROR" thread="6" domain="/LM/W3SVC/6/ROOT-1-130690698608364114" username="HP_ProBook_4340\SiV@S"><message>System.Threading.ThreadAbortException: Поток находился в процессе прерывания.    в System.Threading.Thread.AbortInternal()    в System.Threading.Thread.Abort(Object stateInfo)    в System.Web.HttpResponse.AbortCurrentThread()    в System.Web.HttpResponse.End()    в System.Web.HttpResponse.Redirect(String url, Boolean endResponse, Boolean permanent)    в System.Web.HttpResponse.Redirect(String url)    в KPIWeb.Account.Login.LogIn(Object sender, EventArgs e) в c:\Users\SiV@S\Desktop\Repo\Projects.git\trunk\KPIproduction\KPIWeb\KPIWeb\Account\Login.aspx.cs:строка 54KPIWeb.LogWriter  Void WriteError(System.Exception) Line Number: 0</message><properties><data name="log4net:HostName" value="HP_ProBook_4340" /></properties></event>
<event logger="KPIWeb.LogWriter" timestamp="2015-02-22T12:12:45.5123985+03:00" level="ERROR" thread="10" domain="/LM/W3SVC/6/ROOT-1-130690699288843035" username="HP_ProBook_4340\SiV@S"><message>System.Threading.ThreadAbortException: Поток находился в процессе прерывания.    в System.Threading.Thread.AbortInternal()    в System.Threading.Thread.Abort(Object stateInfo)    в System.Web.HttpResponse.AbortCurrentThread()    в System.Web.HttpResponse.End()    в System.Web.HttpResponse.Redirect(String url, Boolean endResponse, Boolean permanent)    в System.Web.HttpResponse.Redirect(String url)    в KPIWeb.Account.Login.LogIn(Object sender, EventArgs e) в c:\Users\SiV@S\Desktop\Repo\Projects.git\trunk\KPIproduction\KPIWeb\KPIWeb\Account\Login.aspx.cs:строка 54KPIWeb.LogWriter  Void WriteError(System.Exception) Line Number: 0</message><properties><data name="log4net:HostName" value="HP_ProBook_4340" /></properties></event>
<event logger="KPIWeb.LogWriter" timestamp="2015-02-22T12:14:02.9658286+03:00" level="ERROR" thread="6" domain="/LM/W3SVC/6/ROOT-1-130690700079448255" username="HP_ProBook_4340\SiV@S"><message>System.Threading.ThreadAbortException: Поток находился в процессе прерывания.    в System.Threading.Thread.AbortInternal()    в System.Threading.Thread.Abort(Object stateInfo)    в System.Web.HttpResponse.AbortCurrentThread()    в System.Web.HttpResponse.End()    в System.Web.HttpResponse.Redirect(String url, Boolean endResponse, Boolean permanent)    в System.Web.HttpResponse.Redirect(String url)    в KPIWeb.Account.Login.LogIn(Object sender, EventArgs e) в c:\Users\SiV@S\Desktop\Repo\Projects.git\trunk\KPIproduction\KPIWeb\KPIWeb\Account\Login.aspx.cs:строка 54KPIWeb.LogWriter  Void WriteError(System.Exception) Line Number: 0</message><properties><data name="log4net:HostName" value="HP_ProBook_4340" /></properties></event>
<event logger="KPIWeb.LogWriter" timestamp="2015-02-22T12:15:50.6819896+03:00" level="ERROR" thread="5" domain="/LM/W3SVC/6/ROOT-1-130690701161710157" username="HP_ProBook_4340\SiV@S"><message>System.Threading.ThreadAbortException: Поток находился в процессе прерывания.    в System.Threading.Thread.AbortInternal()    в System.Threading.Thread.Abort(Object stateInfo)    в System.Web.HttpResponse.AbortCurrentThread()    в System.Web.HttpResponse.End()    в System.Web.HttpResponse.Redirect(String url, Boolean endResponse, Boolean permanent)    в System.Web.HttpResponse.Redirect(String url)    в KPIWeb.Account.Login.LogIn(Object sender, EventArgs e) в c:\Users\SiV@S\Desktop\Repo\Projects.git\trunk\KPIproduction\KPIWeb\KPIWeb\Account\Login.aspx.cs:строка 54KPIWeb.LogWriter  Void WriteError(System.Exception) Line Number: 0</message><properties><data name="log4net:HostName" value="HP_ProBook_4340" /></properties></event>
<event logger="KPIWeb.LogWriter" timestamp="2015-02-22T12:20:03.3994442+03:00" level="ERROR" thread="7" domain="/LM/W3SVC/6/ROOT-1-130690703795680811" username="HP_ProBook_4340\SiV@S"><message>System.Threading.ThreadAbortException: Поток находился в процессе прерывания.    в System.Threading.Thread.AbortInternal()    в System.Threading.Thread.Abort(Object stateInfo)    в System.Web.HttpResponse.AbortCurrentThread()    в System.Web.HttpResponse.End()    в System.Web.HttpResponse.Redirect(String url, Boolean endResponse, Boolean permanent)    в System.Web.HttpResponse.Redirect(String url)    в KPIWeb.Account.Login.LogIn(Object sender, EventArgs e) в c:\Users\SiV@S\Desktop\Repo\Projects.git\trunk\KPIproduction\KPIWeb\KPIWeb\Account\Login.aspx.cs:строка 54KPIWeb.LogWriter  Void WriteError(System.Exception) Line Number: 0</message><properties><data name="log4net:HostName" value="HP_ProBook_4340" /></properties></event>
<event logger="KPIWeb.LogWriter" timestamp="2015-02-22T12:21:42.8531326+03:00" level="ERROR" thread="6" domain="/LM/W3SVC/6/ROOT-1-130690704796488054" username="HP_ProBook_4340\SiV@S"><message>System.Threading.ThreadAbortException: Поток находился в процессе прерывания.    в System.Threading.Thread.AbortInternal()    в System.Threading.Thread.Abort(Object stateInfo)    в System.Web.HttpResponse.AbortCurrentThread()    в System.Web.HttpResponse.End()    в System.Web.HttpResponse.Redirect(String url, Boolean endResponse, Boolean permanent)    в System.Web.HttpResponse.Redirect(String url)    в KPIWeb.Account.Login.LogIn(Object sender, EventArgs e) в c:\Users\SiV@S\Desktop\Repo\Projects.git\trunk\KPIproduction\KPIWeb\KPIWeb\Account\Login.aspx.cs:строка 54KPIWeb.LogWriter  Void WriteError(System.Exception) Line Number: 0</message><properties><data name="log4net:HostName" value="HP_ProBook_4340" /></properties></event>
<event logger="KPIWeb.LogWriter" timestamp="2015-02-22T12:29:00.472163+03:00" level="ERROR" thread="5" domain="/LM/W3SVC/6/ROOT-1-130690709163087810" username="HP_ProBook_4340\SiV@S"><message>System.Threading.ThreadAbortException: Поток находился в процессе прерывания.    в System.Threading.Thread.AbortInternal()    в System.Threading.Thread.Abort(Object stateInfo)    в System.Web.HttpResponse.AbortCurrentThread()    в System.Web.HttpResponse.End()    в System.Web.HttpResponse.Redirect(String url, Boolean endResponse, Boolean permanent)    в System.Web.HttpResponse.Redirect(String url)    в KPIWeb.Account.Login.LogIn(Object sender, EventArgs e) в c:\Users\SiV@S\Desktop\Repo\Projects.git\trunk\KPIproduction\KPIWeb\KPIWeb\Account\Login.aspx.cs:строка 54KPIWeb.LogWriter  Void WriteError(System.Exception) Line Number: 0</message><properties><data name="log4net:HostName" value="HP_ProBook_4340" /></properties></event>
<event logger="KPIWeb.LogWriter" timestamp="2015-02-22T12:35:16.717683+03:00" level="ERROR" thread="9" domain="/LM/W3SVC/6/ROOT-1-130690712905251849" username="HP_ProBook_4340\SiV@S"><message>System.Threading.ThreadAbortException: Поток находился в процессе прерывания.    в System.Threading.Thread.AbortInternal()    в System.Threading.Thread.Abort(Object stateInfo)    в System.Web.HttpResponse.AbortCurrentThread()    в System.Web.HttpResponse.End()    в System.Web.HttpResponse.Redirect(String url, Boolean endResponse, Boolean permanent)    в System.Web.HttpResponse.Redirect(String url)    в KPIWeb.Account.Login.LogIn(Object sender, EventArgs e) в c:\Users\SiV@S\Desktop\Repo\Projects.git\trunk\KPIproduction\KPIWeb\KPIWeb\Account\Login.aspx.cs:строка 54KPIWeb.LogWriter  Void WriteError(System.Exception) Line Number: 0</message><properties><data name="log4net:HostName" value="HP_ProBook_4340" /></properties></event>
<event logger="KPIWeb.LogWriter" timestamp="2015-02-22T13:04:41.4646208+03:00" level="ERROR" thread="5" domain="/LM/W3SVC/6/ROOT-1-130690730160168774" username="HP_ProBook_4340\SiV@S"><message>System.Threading.ThreadAbortException: Поток находился в процессе прерывания.    в System.Threading.Thread.AbortInternal()    в System.Threading.Thread.Abort(Object stateInfo)    в System.Web.HttpResponse.AbortCurrentThread()    в System.Web.HttpResponse.End()    в System.Web.HttpResponse.Redirect(String url, Boolean endResponse, Boolean permanent)    в System.Web.HttpResponse.Redirect(String url)    в KPIWeb.Account.Login.LogIn(Object sender, EventArgs e) в c:\Users\SiV@S\Desktop\Repo\Projects.git\trunk\KPIproduction\KPIWeb\KPIWeb\Account\Login.aspx.cs:строка 54KPIWeb.LogWriter  Void WriteError(System.Exception) Line Number: 0</message><properties><data name="log4net:HostName" value="HP_ProBook_4340" /></properties></event>
<event logger="KPIWeb.LogWriter" timestamp="2015-02-22T13:08:30.4947206+03:00" level="ERROR" thread="8" domain="/LM/W3SVC/6/ROOT-1-130690732882814500" username="HP_ProBook_4340\SiV@S"><message>System.Threading.ThreadAbortException: Поток находился в процессе прерывания.    в System.Threading.Thread.AbortInternal()    в System.Threading.Thread.Abort(Object stateInfo)    в System.Web.HttpResponse.AbortCurrentThread()    в System.Web.HttpResponse.End()    в System.Web.HttpResponse.Redirect(String url, Boolean endResponse, Boolean permanent)    в System.Web.HttpResponse.Redirect(String url)    в KPIWeb.Account.Login.LogIn(Object sender, EventArgs e) в c:\Users\SiV@S\Desktop\Repo\Projects.git\trunk\KPIproduction\KPIWeb\KPIWeb\Account\Login.aspx.cs:строка 54KPIWeb.LogWriter  Void WriteError(System.Exception) Line Number: 0</message><properties><data name="log4net:HostName" value="HP_ProBook_4340" /></properties></event>
<event logger="KPIWeb.LogWriter" timestamp="2015-02-22T13:22:14.9678777+03:00" level="ERROR" thread="9" domain="/LM/W3SVC/6/ROOT-1-130690741120725682" username="HP_ProBook_4340\SiV@S"><message>System.Threading.ThreadAbortException: Поток находился в процессе прерывания.    в System.Threading.Thread.AbortInternal()    в System.Threading.Thread.Abort(Object stateInfo)    в System.Web.HttpResponse.AbortCurrentThread()    в System.Web.HttpResponse.End()    в System.Web.HttpResponse.Redirect(String url, Boolean endResponse, Boolean permanent)    в System.Web.HttpResponse.Redirect(String url)    в KPIWeb.Account.Login.LogIn(Object sender, EventArgs e) в c:\Users\SiV@S\Desktop\Repo\Projects.git\trunk\KPIproduction\KPIWeb\KPIWeb\Account\Login.aspx.cs:строка 54KPIWeb.LogWriter  Void WriteError(System.Exception) Line Number: 0</message><properties><data name="log4net:HostName" value="HP_ProBook_4340" /></properties></event>
<event logger="KPIWeb.LogWriter" timestamp="2015-02-22T13:30:58.1138+03:00" level="ERROR" thread="6" domain="/LM/W3SVC/6/ROOT-1-130690746326173416" username="HP_ProBook_4340\SiV@S"><message>System.Threading.ThreadAbortException: Поток находился в процессе прерывания.    в System.Threading.Thread.AbortInternal()    в System.Threading.Thread.Abort(Object stateInfo)    в System.Web.HttpResponse.AbortCurrentThread()    в System.Web.HttpResponse.End()    в System.Web.HttpResponse.Redirect(String url, Boolean endResponse, Boolean permanent)    в System.Web.HttpResponse.Redirect(String url)    в KPIWeb.Account.Login.LogIn(Object sender, EventArgs e) в c:\Users\SiV@S\Desktop\Repo\Projects.git\trunk\KPIproduction\KPIWeb\KPIWeb\Account\Login.aspx.cs:строка 54KPIWeb.LogWriter  Void WriteError(System.Exception) Line Number: 0</message><properties><data name="log4net:HostName" value="HP_ProBook_4340" /></properties></event>
<event logger="KPIWeb.LogWriter" timestamp="2015-02-22T13:33:07.9232246+03:00" level="ERROR" thread="7" domain="/LM/W3SVC/6/ROOT-1-130690747326710644" username="HP_ProBook_4340\SiV@S"><message>System.Threading.ThreadAbortException: Поток находился в процессе прерывания.    в System.Threading.Thread.AbortInternal()    в System.Threading.Thread.Abort(Object stateInfo)    в System.Web.HttpResponse.AbortCurrentThread()    в System.Web.HttpResponse.End()    в System.Web.HttpResponse.Redirect(String url, Boolean endResponse, Boolean permanent)    в System.Web.HttpResponse.Redirect(String url)    в KPIWeb.Account.Login.LogIn(Object sender, EventArgs e) в c:\Users\SiV@S\Desktop\Repo\Projects.git\trunk\KPIproduction\KPIWeb\KPIWeb\Account\Login.aspx.cs:строка 54KPIWeb.LogWriter  Void WriteError(System.Exception) Line Number: 0</message><properties><data name="log4net:HostName" value="HP_ProBook_4340" /></properties></event>
<event logger="KPIWeb.LogWriter" timestamp="2015-02-22T13:35:24.73805+03:00" level="ERROR" thread="10" domain="/LM/W3SVC/6/ROOT-1-130690748846737584" username="HP_ProBook_4340\SiV@S"><message>System.Threading.ThreadAbortException: Поток находился в процессе прерывания.    в System.Threading.Thread.AbortInternal()    в System.Threading.Thread.Abort(Object stateInfo)    в System.Web.HttpResponse.AbortCurrentThread()    в System.Web.HttpResponse.End()    в System.Web.HttpResponse.Redirect(String url, Boolean endResponse, Boolean permanent)    в System.Web.HttpResponse.Redirect(String url)    в KPIWeb.Account.Login.LogIn(Object sender, EventArgs e) в c:\Users\SiV@S\Desktop\Repo\Projects.git\trunk\KPIproduction\KPIWeb\KPIWeb\Account\Login.aspx.cs:строка 54KPIWeb.LogWriter  Void WriteError(System.Exception) Line Number: 0</message><properties><data name="log4net:HostName" value="HP_ProBook_4340" /></properties></event>
<event logger="KPIWeb.LogWriter" timestamp="2015-02-22T13:44:21.0187235+03:00" level="ERROR" thread="7" domain="/LM/W3SVC/6/ROOT-1-130690754373993725" username="HP_ProBook_4340\SiV@S"><message>System.Threading.ThreadAbortException: Поток находился в процессе прерывания.    в System.Threading.Thread.AbortInternal()    в System.Threading.Thread.Abort(Object stateInfo)    в System.Web.HttpResponse.AbortCurrentThread()    в System.Web.HttpResponse.End()    в System.Web.HttpResponse.Redirect(String url, Boolean endResponse, Boolean permanent)    в System.Web.HttpResponse.Redirect(String url)    в KPIWeb.Account.Login.LogIn(Object sender, EventArgs e) в c:\Users\SiV@S\Desktop\Repo\Projects.git\trunk\KPIproduction\KPIWeb\KPIWeb\Account\Login.aspx.cs:строка 54KPIWeb.LogWriter  Void WriteError(System.Exception) Line Number: 0</message><properties><data name="log4net:HostName" value="HP_ProBook_4340" /></properties></event>
<event logger="KPIWeb.LogWriter" timestamp="2015-02-22T13:48:31.5030504+03:00" level="ERROR" thread="7" domain="/LM/W3SVC/6/ROOT-1-130690756537177452" username="HP_ProBook_4340\SiV@S"><message>System.Threading.ThreadAbortException: Поток находился в процессе прерывания.    в System.Threading.Thread.AbortInternal()    в System.Threading.Thread.Abort(Object stateInfo)    в System.Web.HttpResponse.AbortCurrentThread()    в System.Web.HttpResponse.End()    в System.Web.HttpResponse.Redirect(String url, Boolean endResponse, Boolean permanent)    в System.Web.HttpResponse.Redirect(String url)    в KPIWeb.Account.Login.LogIn(Object sender, EventArgs e) в c:\Users\SiV@S\Desktop\Repo\Projects.git\trunk\KPIproduction\KPIWeb\KPIWeb\Account\Login.aspx.cs:строка 54KPIWeb.LogWriter  Void WriteError(System.Exception) Line Number: 0</message><properties><data name="log4net:HostName" value="HP_ProBook_4340" /></properties></event>
<event logger="KPIWeb.LogWriter" timestamp="2015-02-22T13:55:44.1747978+03:00" level="ERROR" thread="8" domain="/LM/W3SVC/6/ROOT-1-130690761205964492" username="HP_ProBook_4340\SiV@S"><message>System.Threading.ThreadAbortException: Поток находился в процессе прерывания.    в System.Threading.Thread.AbortInternal()    в System.Threading.Thread.Abort(Object stateInfo)    в System.Web.HttpResponse.AbortCurrentThread()    в System.Web.HttpResponse.End()    в System.Web.HttpResponse.Redirect(String url, Boolean endResponse, Boolean permanent)    в System.Web.HttpResponse.Redirect(String url)    в KPIWeb.Account.Login.LogIn(Object sender, EventArgs e) в c:\Users\SiV@S\Desktop\Repo\Projects.git\trunk\KPIproduction\KPIWeb\KPIWeb\Account\Login.aspx.cs:строка 54KPIWeb.LogWriter  Void WriteError(System.Exception) Line Number: 0</message><properties><data name="log4net:HostName" value="HP_ProBook_4340" /></properties></event>
<event logger="KPIWeb.LogWriter" timestamp="2015-02-22T13:57:51.1310593+03:00" level="ERROR" thread="10" domain="/LM/W3SVC/6/ROOT-1-130690762467826666" username="HP_ProBook_4340\SiV@S"><message>System.Threading.ThreadAbortException: Поток находился в процессе прерывания.    в System.Threading.Thread.AbortInternal()    в System.Threading.Thread.Abort(Object stateInfo)    в System.Web.HttpResponse.AbortCurrentThread()    в System.Web.HttpResponse.End()    в System.Web.HttpResponse.Redirect(String url, Boolean endResponse, Boolean permanent)    в System.Web.HttpResponse.Redirect(String url)    в KPIWeb.Account.Login.LogIn(Object sender, EventArgs e) в c:\Users\SiV@S\Desktop\Repo\Projects.git\trunk\KPIproduction\KPIWeb\KPIWeb\Account\Login.aspx.cs:строка 54KPIWeb.LogWriter  Void WriteError(System.Exception) Line Number: 0</message><properties><data name="log4net:HostName" value="HP_ProBook_4340" /></properties></event>
<event logger="KPIWeb.LogWriter" timestamp="2015-02-22T13:58:44.9801393+03:00" level="ERROR" thread="8" domain="/LM/W3SVC/6/ROOT-1-130690762991686629" username="HP_ProBook_4340\SiV@S"><message>System.Threading.ThreadAbortException: Поток находился в процессе прерывания.    в System.Threading.Thread.AbortInternal()    в System.Threading.Thread.Abort(Object stateInfo)    в System.Web.HttpResponse.AbortCurrentThread()    в System.Web.HttpResponse.End()    в System.Web.HttpResponse.Redirect(String url, Boolean endResponse, Boolean permanent)    в System.Web.HttpResponse.Redirect(String url)    в KPIWeb.Account.Login.LogIn(Object sender, EventArgs e) в c:\Users\SiV@S\Desktop\Repo\Projects.git\trunk\KPIproduction\KPIWeb\KPIWeb\Account\Login.aspx.cs:строка 54KPIWeb.LogWriter  Void WriteError(System.Exception) Line Number: 0</message><properties><data name="log4net:HostName" value="HP_ProBook_4340" /></properties></event>
<event logger="KPIWeb.LogWriter" timestamp="2015-02-22T14:00:42.9568871+03:00" level="ERROR" thread="8" domain="/LM/W3SVC/6/ROOT-1-130690764158493367" username="HP_ProBook_4340\SiV@S"><message>System.Threading.ThreadAbortException: Поток находился в процессе прерывания.    в System.Threading.Thread.AbortInternal()    в System.Threading.Thread.Abort(Object stateInfo)    в System.Web.HttpResponse.AbortCurrentThread()    в System.Web.HttpResponse.End()    в System.Web.HttpResponse.Redirect(String url, Boolean endResponse, Boolean permanent)    в System.Web.HttpResponse.Redirect(String url)    в KPIWeb.Account.Login.LogIn(Object sender, EventArgs e) в c:\Users\SiV@S\Desktop\Repo\Projects.git\trunk\KPIproduction\KPIWeb\KPIWeb\Account\Login.aspx.cs:строка 54KPIWeb.LogWriter  Void WriteError(System.Exception) Line Number: 0</message><properties><data name="log4net:HostName" value="HP_ProBook_4340" /></properties></event>
<event logger="KPIWeb.LogWriter" timestamp="2015-02-22T14:02:23.0816139+03:00" level="ERROR" thread="6" domain="/LM/W3SVC/6/ROOT-1-130690765178231692" username="HP_ProBook_4340\SiV@S"><message>System.Threading.ThreadAbortException: Поток находился в процессе прерывания.    в System.Threading.Thread.AbortInternal()    в System.Threading.Thread.Abort(Object stateInfo)    в System.Web.HttpResponse.AbortCurrentThread()    в System.Web.HttpResponse.End()    в System.Web.HttpResponse.Redirect(String url, Boolean endResponse, Boolean permanent)    в System.Web.HttpResponse.Redirect(String url)    в KPIWeb.Account.Login.LogIn(Object sender, EventArgs e) в c:\Users\SiV@S\Desktop\Repo\Projects.git\trunk\KPIproduction\KPIWeb\KPIWeb\Account\Login.aspx.cs:строка 54KPIWeb.LogWriter  Void WriteError(System.Exception) Line Number: 0</message><properties><data name="log4net:HostName" value="HP_ProBook_4340" /></properties></event>
<event logger="KPIWeb.LogWriter" timestamp="2015-02-22T14:04:15.2160277+03:00" level="ERROR" thread="9" domain="/LM/W3SVC/6/ROOT-1-130690766331717668" username="HP_ProBook_4340\SiV@S"><message>System.Threading.ThreadAbortException: Поток находился в процессе прерывания.    в System.Threading.Thread.AbortInternal()    в System.Threading.Thread.Abort(Object stateInfo)    в System.Web.HttpResponse.AbortCurrentThread()    в System.Web.HttpResponse.End()    в System.Web.HttpResponse.Redirect(String url, Boolean endResponse, Boolean permanent)    в System.Web.HttpResponse.Redirect(String url)    в KPIWeb.Account.Login.LogIn(Object sender, EventArgs e) в c:\Users\SiV@S\Desktop\Repo\Projects.git\trunk\KPIproduction\KPIWeb\KPIWeb\Account\Login.aspx.cs:строка 54KPIWeb.LogWriter  Void WriteError(System.Exception) Line Number: 0</message><properties><data name="log4net:HostName" value="HP_ProBook_4340" /></properties></event>
<event logger="KPIWeb.LogWriter" timestamp="2015-02-22T14:05:29.9253008+03:00" level="ERROR" thread="8" domain="/LM/W3SVC/6/ROOT-1-130690766979014691" username="HP_ProBook_4340\SiV@S"><message>System.Threading.ThreadAbortException: Поток находился в процессе прерывания.    в System.Threading.Thread.AbortInternal()    в System.Threading.Thread.Abort(Object stateInfo)    в System.Web.HttpResponse.AbortCurrentThread()    в System.Web.HttpResponse.End()    в System.Web.HttpResponse.Redirect(String url, Boolean endResponse, Boolean permanent)    в System.Web.HttpResponse.Redirect(String url)    в KPIWeb.Account.Login.LogIn(Object sender, EventArgs e) в c:\Users\SiV@S\Desktop\Repo\Projects.git\trunk\KPIproduction\KPIWeb\KPIWeb\Account\Login.aspx.cs:строка 54KPIWeb.LogWriter  Void WriteError(System.Exception) Line Number: 0</message><properties><data name="log4net:HostName" value="HP_ProBook_4340" /></properties></event>
<event logger="KPIWeb.LogWriter" timestamp="2015-02-22T14:07:36.999569+03:00" level="ERROR" thread="9" domain="/LM/W3SVC/6/ROOT-1-130690768333342154" username="HP_ProBook_4340\SiV@S"><message>System.Threading.ThreadAbortException: Поток находился в процессе прерывания.    в System.Threading.Thread.AbortInternal()    в System.Threading.Thread.Abort(Object stateInfo)    в System.Web.HttpResponse.AbortCurrentThread()    в System.Web.HttpResponse.End()    в System.Web.HttpResponse.Redirect(String url, Boolean endResponse, Boolean permanent)    в System.Web.HttpResponse.Redirect(String url)    в KPIWeb.Account.Login.LogIn(Object sender, EventArgs e) в c:\Users\SiV@S\Desktop\Repo\Projects.git\trunk\KPIproduction\KPIWeb\KPIWeb\Account\Login.aspx.cs:строка 54KPIWeb.LogWriter  Void WriteError(System.Exception) Line Number: 0</message><properties><data name="log4net:HostName" value="HP_ProBook_4340" /></properties></event>
<event logger="KPIWeb.LogWriter" timestamp="2015-02-22T14:08:49.3137052+03:00" level="ERROR" thread="11" domain="/LM/W3SVC/6/ROOT-1-130690769042202699" username="HP_ProBook_4340\SiV@S"><message>System.Threading.ThreadAbortException: Поток находился в процессе прерывания.    в System.Threading.Thread.AbortInternal()    в System.Threading.Thread.Abort(Object stateInfo)    в System.Web.HttpResponse.AbortCurrentThread()    в System.Web.HttpResponse.End()    в System.Web.HttpResponse.Redirect(String url, Boolean endResponse, Boolean permanent)    в System.Web.HttpResponse.Redirect(String url)    в KPIWeb.Account.Login.LogIn(Object sender, EventArgs e) в c:\Users\SiV@S\Desktop\Repo\Projects.git\trunk\KPIproduction\KPIWeb\KPIWeb\Account\Login.aspx.cs:строка 54KPIWeb.LogWriter  Void WriteError(System.Exception) Line Number: 0</message><properties><data name="log4net:HostName" value="HP_ProBook_4340" /></properties></event>
<event logger="KPIWeb.LogWriter" timestamp="2015-02-22T14:09:47.9910613+03:00" level="ERROR" thread="12" domain="/LM/W3SVC/6/ROOT-1-130690769557342163" username="HP_ProBook_4340\SiV@S"><message>System.Threading.ThreadAbortException: Поток находился в процессе прерывания.    в System.Threading.Thread.AbortInternal()    в System.Threading.Thread.Abort(Object stateInfo)    в System.Web.HttpResponse.AbortCurrentThread()    в System.Web.HttpResponse.End()    в System.Web.HttpResponse.Redirect(String url, Boolean endResponse, Boolean permanent)    в System.Web.HttpResponse.Redirect(String url)    в KPIWeb.Account.Login.LogIn(Object sender, EventArgs e) в c:\Users\SiV@S\Desktop\Repo\Projects.git\trunk\KPIproduction\KPIWeb\KPIWeb\Account\Login.aspx.cs:строка 54KPIWeb.LogWriter  Void WriteError(System.Exception) Line Number: 0</message><properties><data name="log4net:HostName" value="HP_ProBook_4340" /></properties></event>
<event logger="KPIWeb.LogWriter" timestamp="2015-02-22T14:12:31.4324096+03:00" level="ERROR" thread="9" domain="/LM/W3SVC/6/ROOT-1-130690771276340484" username="HP_ProBook_4340\SiV@S"><message>System.Threading.ThreadAbortException: Поток находился в процессе прерывания.    в System.Threading.Thread.AbortInternal()    в System.Threading.Thread.Abort(Object stateInfo)    в System.Web.HttpResponse.AbortCurrentThread()    в System.Web.HttpResponse.End()    в System.Web.HttpResponse.Redirect(String url, Boolean endResponse, Boolean permanent)    в System.Web.HttpResponse.Redirect(String url)    в KPIWeb.Account.Login.LogIn(Object sender, EventArgs e) в c:\Users\SiV@S\Desktop\Repo\Projects.git\trunk\KPIproduction\KPIWeb\KPIWeb\Account\Login.aspx.cs:строка 54KPIWeb.LogWriter  Void WriteError(System.Exception) Line Number: 0</message><properties><data name="log4net:HostName" value="HP_ProBook_4340" /></properties></event>
<event logger="KPIWeb.LogWriter" timestamp="2015-02-22T14:13:59.9534727+03:00" level="ERROR" thread="5" domain="/LM/W3SVC/6/ROOT-1-130690771969070106" username="HP_ProBook_4340\SiV@S"><message>System.Threading.ThreadAbortException: Поток находился в процессе прерывания.    в System.Threading.Thread.AbortInternal()    в System.Threading.Thread.Abort(Object stateInfo)    в System.Web.HttpResponse.AbortCurrentThread()    в System.Web.HttpResponse.End()    в System.Web.HttpResponse.Redirect(String url, Boolean endResponse, Boolean permanent)    в System.Web.HttpResponse.Redirect(String url)    в KPIWeb.Account.Login.LogIn(Object sender, EventArgs e) в c:\Users\SiV@S\Desktop\Repo\Projects.git\trunk\KPIproduction\KPIWeb\KPIWeb\Account\Login.aspx.cs:строка 54KPIWeb.LogWriter  Void WriteError(System.Exception) Line Number: 0</message><properties><data name="log4net:HostName" value="HP_ProBook_4340" /></properties></event>
<event logger="KPIWeb.LogWriter" timestamp="2015-02-22T14:16:36.5284283+03:00" level="ERROR" thread="8" domain="/LM/W3SVC/6/ROOT-1-130690773687518396" username="HP_ProBook_4340\SiV@S"><message>System.Threading.ThreadAbortException: Поток находился в процессе прерывания.    в System.Threading.Thread.AbortInternal()    в System.Threading.Thread.Abort(Object stateInfo)    в System.Web.HttpResponse.AbortCurrentThread()    в System.Web.HttpResponse.End()    в System.Web.HttpResponse.Redirect(String url, Boolean endResponse, Boolean permanent)    в System.Web.HttpResponse.Redirect(String url)    в KPIWeb.Account.Login.LogIn(Object sender, EventArgs e) в c:\Users\SiV@S\Desktop\Repo\Projects.git\trunk\KPIproduction\KPIWeb\KPIWeb\Account\Login.aspx.cs:строка 54KPIWeb.LogWriter  Void WriteError(System.Exception) Line Number: 0</message><properties><data name="log4net:HostName" value="HP_ProBook_4340" /></properties></event>
