<event logger="KPIWeb.LogWriter" timestamp="2015-02-22T11:18:20.0626255+03:00" level="ERROR" thread="12" domain="/LM/W3SVC/6/ROOT-1-130690666551180548" username="HP_ProBook_4340\SiV@S"><message>System.Threading.ThreadAbortException: Поток находился в процессе прерывания.    в System.Threading.Thread.AbortInternal()    в System.Threading.Thread.Abort(Object stateInfo)    в System.Web.HttpResponse.AbortCurrentThread()    в System.Web.HttpResponse.End()    в System.Web.HttpResponse.Redirect(String url, Boolean endResponse, Boolean permanent)    в System.Web.HttpResponse.Redirect(String url)    в KPIWeb.Account.Login.LogIn(Object sender, EventArgs e) в c:\Users\SiV@S\Desktop\Repo\Projects.git\trunk\KPIproduction\KPIWeb\KPIWeb\Account\Login.aspx.cs:строка 54KPIWeb.LogWriter  Void WriteError(System.Exception) Line Number: 0</message><properties><data name="log4net:HostName" value="HP_ProBook_4340" /></properties></event>
<event logger="KPIWeb.LogWriter" timestamp="2015-02-22T11:20:51.0052589+03:00" level="ERROR" thread="9" domain="/LM/W3SVC/6/ROOT-1-130690668300730616" username="HP_ProBook_4340\SiV@S"><message>System.Threading.ThreadAbortException: Поток находился в процессе прерывания.    в System.Threading.Thread.AbortInternal()    в System.Threading.Thread.Abort(Object stateInfo)    в System.Web.HttpResponse.AbortCurrentThread()    в System.Web.HttpResponse.End()    в System.Web.HttpResponse.Redirect(String url, Boolean endResponse, Boolean permanent)    в System.Web.HttpResponse.Redirect(String url)    в KPIWeb.Account.Login.LogIn(Object sender, EventArgs e) в c:\Users\SiV@S\Desktop\Repo\Projects.git\trunk\KPIproduction\KPIWeb\KPIWeb\Account\Login.aspx.cs:строка 54KPIWeb.LogWriter  Void WriteError(System.Exception) Line Number: 0</message><properties><data name="log4net:HostName" value="HP_ProBook_4340" /></properties></event>
<event logger="KPIWeb.LogWriter" timestamp="2015-02-22T11:23:10.6392455+03:00" level="ERROR" thread="8" domain="/LM/W3SVC/6/ROOT-1-130690669490358659" username="HP_ProBook_4340\SiV@S"><message>System.Threading.ThreadAbortException: Поток находился в процессе прерывания.    в System.Threading.Thread.AbortInternal()    в System.Threading.Thread.Abort(Object stateInfo)    в System.Web.HttpResponse.AbortCurrentThread()    в System.Web.HttpResponse.End()    в System.Web.HttpResponse.Redirect(String url, Boolean endResponse, Boolean permanent)    в System.Web.HttpResponse.Redirect(String url)    в KPIWeb.Account.Login.LogIn(Object sender, EventArgs e) в c:\Users\SiV@S\Desktop\Repo\Projects.git\trunk\KPIproduction\KPIWeb\KPIWeb\Account\Login.aspx.cs:строка 54KPIWeb.LogWriter  Void WriteError(System.Exception) Line Number: 0</message><properties><data name="log4net:HostName" value="HP_ProBook_4340" /></properties></event>
<event logger="KPIWeb.LogWriter" timestamp="2015-02-22T11:27:57.0386266+03:00" level="ERROR" thread="19" domain="/LM/W3SVC/6/ROOT-1-130690671050777910" username="HP_ProBook_4340\SiV@S"><message>System.Threading.ThreadAbortException: Поток находился в процессе прерывания.    в System.Threading.Thread.AbortInternal()    в System.Threading.Thread.Abort(Object stateInfo)    в System.Web.HttpResponse.AbortCurrentThread()    в System.Web.HttpResponse.End()    в System.Web.HttpResponse.Redirect(String url, Boolean endResponse, Boolean permanent)    в System.Web.HttpResponse.Redirect(String url)    в KPIWeb.Account.Login.LogIn(Object sender, EventArgs e) в c:\Users\SiV@S\Desktop\Repo\Projects.git\trunk\KPIproduction\KPIWeb\KPIWeb\Account\Login.aspx.cs:строка 54KPIWeb.LogWriter  Void WriteError(System.Exception) Line Number: 0</message><properties><data name="log4net:HostName" value="HP_ProBook_4340" /></properties></event>
<event logger="KPIWeb.LogWriter" timestamp="2015-02-22T11:29:52.8642515+03:00" level="ERROR" thread="7" domain="/LM/W3SVC/6/ROOT-1-130690673726100930" username="HP_ProBook_4340\SiV@S"><message>System.Threading.ThreadAbortException: Поток находился в процессе прерывания.    в System.Threading.Thread.AbortInternal()    в System.Threading.Thread.Abort(Object stateInfo)    в System.Web.HttpResponse.AbortCurrentThread()    в System.Web.HttpResponse.End()    в System.Web.HttpResponse.Redirect(String url, Boolean endResponse, Boolean permanent)    в System.Web.HttpResponse.Redirect(String url)    в KPIWeb.Account.Login.LogIn(Object sender, EventArgs e) в c:\Users\SiV@S\Desktop\Repo\Projects.git\trunk\KPIproduction\KPIWeb\KPIWeb\Account\Login.aspx.cs:строка 54KPIWeb.LogWriter  Void WriteError(System.Exception) Line Number: 0</message><properties><data name="log4net:HostName" value="HP_ProBook_4340" /></properties></event>
<event logger="KPIWeb.LogWriter" timestamp="2015-02-22T11:32:33.6454476+03:00" level="ERROR" thread="7" domain="/LM/W3SVC/6/ROOT-1-130690674913318835" username="HP_ProBook_4340\SiV@S"><message>System.Threading.ThreadAbortException: Поток находился в процессе прерывания.    в System.Threading.Thread.AbortInternal()    в System.Threading.Thread.Abort(Object stateInfo)    в System.Web.HttpResponse.AbortCurrentThread()    в System.Web.HttpResponse.End()    в System.Web.HttpResponse.Redirect(String url, Boolean endResponse, Boolean permanent)    в System.Web.HttpResponse.Redirect(String url)    в KPIWeb.Account.Login.LogIn(Object sender, EventArgs e) в c:\Users\SiV@S\Desktop\Repo\Projects.git\trunk\KPIproduction\KPIWeb\KPIWeb\Account\Login.aspx.cs:строка 54KPIWeb.LogWriter  Void WriteError(System.Exception) Line Number: 0</message><properties><data name="log4net:HostName" value="HP_ProBook_4340" /></properties></event>
<event logger="KPIWeb.LogWriter" timestamp="2015-02-22T11:35:39.7310911+03:00" level="ERROR" thread="9" domain="/LM/W3SVC/6/ROOT-1-130690677065221917" username="HP_ProBook_4340\SiV@S"><message>System.Threading.ThreadAbortException: Поток находился в процессе прерывания.    в System.Threading.Thread.AbortInternal()    в System.Threading.Thread.Abort(Object stateInfo)    в System.Web.HttpResponse.AbortCurrentThread()    в System.Web.HttpResponse.End()    в System.Web.HttpResponse.Redirect(String url, Boolean endResponse, Boolean permanent)    в System.Web.HttpResponse.Redirect(String url)    в KPIWeb.Account.Login.LogIn(Object sender, EventArgs e) в c:\Users\SiV@S\Desktop\Repo\Projects.git\trunk\KPIproduction\KPIWeb\KPIWeb\Account\Login.aspx.cs:строка 54KPIWeb.LogWriter  Void WriteError(System.Exception) Line Number: 0</message><properties><data name="log4net:HostName" value="HP_ProBook_4340" /></properties></event>
<event logger="KPIWeb.LogWriter" timestamp="2015-02-22T11:37:59.5840902+03:00" level="ERROR" thread="7" domain="/LM/W3SVC/6/ROOT-1-130690678455641444" username="HP_ProBook_4340\SiV@S"><message>System.Threading.ThreadAbortException: Поток находился в процессе прерывания.    в System.Threading.Thread.AbortInternal()    в System.Threading.Thread.Abort(Object stateInfo)    в System.Web.HttpResponse.AbortCurrentThread()    в System.Web.HttpResponse.End()    в System.Web.HttpResponse.Redirect(String url, Boolean endResponse, Boolean permanent)    в System.Web.HttpResponse.Redirect(String url)    в KPIWeb.Account.Login.LogIn(Object sender, EventArgs e) в c:\Users\SiV@S\Desktop\Repo\Projects.git\trunk\KPIproduction\KPIWeb\KPIWeb\Account\Login.aspx.cs:строка 54KPIWeb.LogWriter  Void WriteError(System.Exception) Line Number: 0</message><properties><data name="log4net:HostName" value="HP_ProBook_4340" /></properties></event>
<event logger="KPIWeb.LogWriter" timestamp="2015-02-22T11:39:07.3729675+03:00" level="ERROR" thread="11" domain="/LM/W3SVC/6/ROOT-1-130690679215024878" username="HP_ProBook_4340\SiV@S"><message>System.Threading.ThreadAbortException: Поток находился в процессе прерывания.    в System.Threading.Thread.AbortInternal()    в System.Threading.Thread.Abort(Object stateInfo)    в System.Web.HttpResponse.AbortCurrentThread()    в System.Web.HttpResponse.End()    в System.Web.HttpResponse.Redirect(String url, Boolean endResponse, Boolean permanent)    в System.Web.HttpResponse.Redirect(String url)    в KPIWeb.Account.Login.LogIn(Object sender, EventArgs e) в c:\Users\SiV@S\Desktop\Repo\Projects.git\trunk\KPIproduction\KPIWeb\KPIWeb\Account\Login.aspx.cs:строка 54KPIWeb.LogWriter  Void WriteError(System.Exception) Line Number: 0</message><properties><data name="log4net:HostName" value="HP_ProBook_4340" /></properties></event>
<event logger="KPIWeb.LogWriter" timestamp="2015-02-22T11:40:40.9853219+03:00" level="ERROR" thread="7" domain="/LM/W3SVC/6/ROOT-1-130690680128097103" username="HP_ProBook_4340\SiV@S"><message>System.Threading.ThreadAbortException: Поток находился в процессе прерывания.    в System.Threading.Thread.AbortInternal()    в System.Threading.Thread.Abort(Object stateInfo)    в System.Web.HttpResponse.AbortCurrentThread()    в System.Web.HttpResponse.End()    в System.Web.HttpResponse.Redirect(String url, Boolean endResponse, Boolean permanent)    в System.Web.HttpResponse.Redirect(String url)    в KPIWeb.Account.Login.LogIn(Object sender, EventArgs e) в c:\Users\SiV@S\Desktop\Repo\Projects.git\trunk\KPIproduction\KPIWeb\KPIWeb\Account\Login.aspx.cs:строка 54KPIWeb.LogWriter  Void WriteError(System.Exception) Line Number: 0</message><properties><data name="log4net:HostName" value="HP_ProBook_4340" /></properties></event>
<event logger="KPIWeb.LogWriter" timestamp="2015-02-22T11:43:12.1919704+03:00" level="ERROR" thread="9" domain="/LM/W3SVC/6/ROOT-1-130690681677075700" username="HP_ProBook_4340\SiV@S"><message>System.Threading.ThreadAbortException: Поток находился в процессе прерывания.    в System.Threading.Thread.AbortInternal()    в System.Threading.Thread.Abort(Object stateInfo)    в System.Web.HttpResponse.AbortCurrentThread()    в System.Web.HttpResponse.End()    в System.Web.HttpResponse.Redirect(String url, Boolean endResponse, Boolean permanent)    в System.Web.HttpResponse.Redirect(String url)    в KPIWeb.Account.Login.LogIn(Object sender, EventArgs e) в c:\Users\SiV@S\Desktop\Repo\Projects.git\trunk\KPIproduction\KPIWeb\KPIWeb\Account\Login.aspx.cs:строка 54KPIWeb.LogWriter  Void WriteError(System.Exception) Line Number: 0</message><properties><data name="log4net:HostName" value="HP_ProBook_4340" /></properties></event>
<event logger="KPIWeb.LogWriter" timestamp="2015-02-22T11:44:33.710633+03:00" level="ERROR" thread="10" domain="/LM/W3SVC/6/ROOT-1-130690682497742639" username="HP_ProBook_4340\SiV@S"><message>System.Threading.ThreadAbortException: Поток находился в процессе прерывания.    в System.Threading.Thread.AbortInternal()    в System.Threading.Thread.Abort(Object stateInfo)    в System.Web.HttpResponse.AbortCurrentThread()    в System.Web.HttpResponse.End()    в System.Web.HttpResponse.Redirect(String url, Boolean endResponse, Boolean permanent)    в System.Web.HttpResponse.Redirect(String url)    в KPIWeb.Account.Login.LogIn(Object sender, EventArgs e) в c:\Users\SiV@S\Desktop\Repo\Projects.git\trunk\KPIproduction\KPIWeb\KPIWeb\Account\Login.aspx.cs:строка 54KPIWeb.LogWriter  Void WriteError(System.Exception) Line Number: 0</message><properties><data name="log4net:HostName" value="HP_ProBook_4340" /></properties></event>
<event logger="KPIWeb.LogWriter" timestamp="2015-02-22T11:47:59.2703903+03:00" level="ERROR" thread="10" domain="/LM/W3SVC/6/ROOT-1-130690684485976359" username="HP_ProBook_4340\SiV@S"><message>System.Threading.ThreadAbortException: Поток находился в процессе прерывания.    в System.Threading.Thread.AbortInternal()    в System.Threading.Thread.Abort(Object stateInfo)    в System.Web.HttpResponse.AbortCurrentThread()    в System.Web.HttpResponse.End()    в System.Web.HttpResponse.Redirect(String url, Boolean endResponse, Boolean permanent)    в System.Web.HttpResponse.Redirect(String url)    в KPIWeb.Account.Login.LogIn(Object sender, EventArgs e) в c:\Users\SiV@S\Desktop\Repo\Projects.git\trunk\KPIproduction\KPIWeb\KPIWeb\Account\Login.aspx.cs:строка 54KPIWeb.LogWriter  Void WriteError(System.Exception) Line Number: 0</message><properties><data name="log4net:HostName" value="HP_ProBook_4340" /></properties></event>
<event logger="KPIWeb.LogWriter" timestamp="2015-02-22T11:49:34.5198383+03:00" level="ERROR" thread="12" domain="/LM/W3SVC/6/ROOT-1-130690685359486321" username="HP_ProBook_4340\SiV@S"><message>System.Threading.ThreadAbortException: Поток находился в процессе прерывания.    в System.Threading.Thread.AbortInternal()    в System.Threading.Thread.Abort(Object stateInfo)    в System.Web.HttpResponse.AbortCurrentThread()    в System.Web.HttpResponse.End()    в System.Web.HttpResponse.Redirect(String url, Boolean endResponse, Boolean permanent)    в System.Web.HttpResponse.Redirect(String url)    в KPIWeb.Account.Login.LogIn(Object sender, EventArgs e) в c:\Users\SiV@S\Desktop\Repo\Projects.git\trunk\KPIproduction\KPIWeb\KPIWeb\Account\Login.aspx.cs:строка 54KPIWeb.LogWriter  Void WriteError(System.Exception) Line Number: 0</message><properties><data name="log4net:HostName" value="HP_ProBook_4340" /></properties></event>
<event logger="KPIWeb.LogWriter" timestamp="2015-02-22T11:51:39.1609674+03:00" level="ERROR" thread="8" domain="/LM/W3SVC/6/ROOT-1-130690686690972478" username="HP_ProBook_4340\SiV@S"><message>System.Threading.ThreadAbortException: Поток находился в процессе прерывания.    в System.Threading.Thread.AbortInternal()    в System.Threading.Thread.Abort(Object stateInfo)    в System.Web.HttpResponse.AbortCurrentThread()    в System.Web.HttpResponse.End()    в System.Web.HttpResponse.Redirect(String url, Boolean endResponse, Boolean permanent)    в System.Web.HttpResponse.Redirect(String url)    в KPIWeb.Account.Login.LogIn(Object sender, EventArgs e) в c:\Users\SiV@S\Desktop\Repo\Projects.git\trunk\KPIproduction\KPIWeb\KPIWeb\Account\Login.aspx.cs:строка 54KPIWeb.LogWriter  Void WriteError(System.Exception) Line Number: 0</message><properties><data name="log4net:HostName" value="HP_ProBook_4340" /></properties></event>
<event logger="KPIWeb.LogWriter" timestamp="2015-02-22T11:52:31.8049784+03:00" level="ERROR" thread="10" domain="/LM/W3SVC/6/ROOT-1-130690687258224923" username="HP_ProBook_4340\SiV@S"><message>System.Threading.ThreadAbortException: Поток находился в процессе прерывания.    в System.Threading.Thread.AbortInternal()    в System.Threading.Thread.Abort(Object stateInfo)    в System.Web.HttpResponse.AbortCurrentThread()    в System.Web.HttpResponse.End()    в System.Web.HttpResponse.Redirect(String url, Boolean endResponse, Boolean permanent)    в System.Web.HttpResponse.Redirect(String url)    в KPIWeb.Account.Login.LogIn(Object sender, EventArgs e) в c:\Users\SiV@S\Desktop\Repo\Projects.git\trunk\KPIproduction\KPIWeb\KPIWeb\Account\Login.aspx.cs:строка 54KPIWeb.LogWriter  Void WriteError(System.Exception) Line Number: 0</message><properties><data name="log4net:HostName" value="HP_ProBook_4340" /></properties></event>
<event logger="KPIWeb.LogWriter" timestamp="2015-02-22T11:55:37.4165948+03:00" level="ERROR" thread="7" domain="/LM/W3SVC/6/ROOT-1-130690688981593494" username="HP_ProBook_4340\SiV@S"><message>System.Threading.ThreadAbortException: Поток находился в процессе прерывания.    в System.Threading.Thread.AbortInternal()    в System.Threading.Thread.Abort(Object stateInfo)    в System.Web.HttpResponse.AbortCurrentThread()    в System.Web.HttpResponse.End()    в System.Web.HttpResponse.Redirect(String url, Boolean endResponse, Boolean permanent)    в System.Web.HttpResponse.Redirect(String url)    в KPIWeb.Account.Login.LogIn(Object sender, EventArgs e) в c:\Users\SiV@S\Desktop\Repo\Projects.git\trunk\KPIproduction\KPIWeb\KPIWeb\Account\Login.aspx.cs:строка 54KPIWeb.LogWriter  Void WriteError(System.Exception) Line Number: 0</message><properties><data name="log4net:HostName" value="HP_ProBook_4340" /></properties></event>
<event logger="KPIWeb.LogWriter" timestamp="2015-02-22T11:56:39.7581605+03:00" level="ERROR" thread="8" domain="/LM/W3SVC/6/ROOT-1-130690689747257288" username="HP_ProBook_4340\SiV@S"><message>System.Threading.ThreadAbortException: Поток находился в процессе прерывания.    в System.Threading.Thread.AbortInternal()    в System.Threading.Thread.Abort(Object stateInfo)    в System.Web.HttpResponse.AbortCurrentThread()    в System.Web.HttpResponse.End()    в System.Web.HttpResponse.Redirect(String url, Boolean endResponse, Boolean permanent)    в System.Web.HttpResponse.Redirect(String url)    в KPIWeb.Account.Login.LogIn(Object sender, EventArgs e) в c:\Users\SiV@S\Desktop\Repo\Projects.git\trunk\KPIproduction\KPIWeb\KPIWeb\Account\Login.aspx.cs:строка 54KPIWeb.LogWriter  Void WriteError(System.Exception) Line Number: 0</message><properties><data name="log4net:HostName" value="HP_ProBook_4340" /></properties></event>
<event logger="KPIWeb.LogWriter" timestamp="2015-02-22T11:57:36.5034062+03:00" level="ERROR" thread="8" domain="/LM/W3SVC/6/ROOT-1-130690690322280177" username="HP_ProBook_4340\SiV@S"><message>System.Threading.ThreadAbortException: Поток находился в процессе прерывания.    в System.Threading.Thread.AbortInternal()    в System.Threading.Thread.Abort(Object stateInfo)    в System.Web.HttpResponse.AbortCurrentThread()    в System.Web.HttpResponse.End()    в System.Web.HttpResponse.Redirect(String url, Boolean endResponse, Boolean permanent)    в System.Web.HttpResponse.Redirect(String url)    в KPIWeb.Account.Login.LogIn(Object sender, EventArgs e) в c:\Users\SiV@S\Desktop\Repo\Projects.git\trunk\KPIproduction\KPIWeb\KPIWeb\Account\Login.aspx.cs:строка 54KPIWeb.LogWriter  Void WriteError(System.Exception) Line Number: 0</message><properties><data name="log4net:HostName" value="HP_ProBook_4340" /></properties></event>
<event logger="KPIWeb.LogWriter" timestamp="2015-02-22T11:58:45.0113246+03:00" level="ERROR" thread="8" domain="/LM/W3SVC/6/ROOT-1-130690691011499598" username="HP_ProBook_4340\SiV@S"><message>System.Threading.ThreadAbortException: Поток находился в процессе прерывания.    в System.Threading.Thread.AbortInternal()    в System.Threading.Thread.Abort(Object stateInfo)    в System.Web.HttpResponse.AbortCurrentThread()    в System.Web.HttpResponse.End()    в System.Web.HttpResponse.Redirect(String url, Boolean endResponse, Boolean permanent)    в System.Web.HttpResponse.Redirect(String url)    в KPIWeb.Account.Login.LogIn(Object sender, EventArgs e) в c:\Users\SiV@S\Desktop\Repo\Projects.git\trunk\KPIproduction\KPIWeb\KPIWeb\Account\Login.aspx.cs:строка 54KPIWeb.LogWriter  Void WriteError(System.Exception) Line Number: 0</message><properties><data name="log4net:HostName" value="HP_ProBook_4340" /></properties></event>
<event logger="KPIWeb.LogWriter" timestamp="2015-02-22T11:59:31.9940119+03:00" level="ERROR" thread="10" domain="/LM/W3SVC/6/ROOT-1-130690691490096972" username="HP_ProBook_4340\SiV@S"><message>System.Threading.ThreadAbortException: Поток находился в процессе прерывания.    в System.Threading.Thread.AbortInternal()    в System.Threading.Thread.Abort(Object stateInfo)    в System.Web.HttpResponse.AbortCurrentThread()    в System.Web.HttpResponse.End()    в System.Web.HttpResponse.Redirect(String url, Boolean endResponse, Boolean permanent)    в System.Web.HttpResponse.Redirect(String url)    в KPIWeb.Account.Login.LogIn(Object sender, EventArgs e) в c:\Users\SiV@S\Desktop\Repo\Projects.git\trunk\KPIproduction\KPIWeb\KPIWeb\Account\Login.aspx.cs:строка 54KPIWeb.LogWriter  Void WriteError(System.Exception) Line Number: 0</message><properties><data name="log4net:HostName" value="HP_ProBook_4340" /></properties></event>
<event logger="KPIWeb.LogWriter" timestamp="2015-02-22T12:01:32.5949098+03:00" level="ERROR" thread="11" domain="/LM/W3SVC/6/ROOT-1-130690692643142923" username="HP_ProBook_4340\SiV@S"><message>System.Threading.ThreadAbortException: Поток находился в процессе прерывания.    в System.Threading.Thread.AbortInternal()    в System.Threading.Thread.Abort(Object stateInfo)    в System.Web.HttpResponse.AbortCurrentThread()    в System.Web.HttpResponse.End()    в System.Web.HttpResponse.Redirect(String url, Boolean endResponse, Boolean permanent)    в System.Web.HttpResponse.Redirect(String url)    в KPIWeb.Account.Login.LogIn(Object sender, EventArgs e) в c:\Users\SiV@S\Desktop\Repo\Projects.git\trunk\KPIproduction\KPIWeb\KPIWeb\Account\Login.aspx.cs:строка 54KPIWeb.LogWriter  Void WriteError(System.Exception) Line Number: 0</message><properties><data name="log4net:HostName" value="HP_ProBook_4340" /></properties></event>
<event logger="KPIWeb.LogWriter" timestamp="2015-02-22T12:02:26.1419725+03:00" level="ERROR" thread="8" domain="/LM/W3SVC/6/ROOT-1-130690693206645153" username="HP_ProBook_4340\SiV@S"><message>System.Threading.ThreadAbortException: Поток находился в процессе прерывания.    в System.Threading.Thread.AbortInternal()    в System.Threading.Thread.Abort(Object stateInfo)    в System.Web.HttpResponse.AbortCurrentThread()    в System.Web.HttpResponse.End()    в System.Web.HttpResponse.Redirect(String url, Boolean endResponse, Boolean permanent)    в System.Web.HttpResponse.Redirect(String url)    в KPIWeb.Account.Login.LogIn(Object sender, EventArgs e) в c:\Users\SiV@S\Desktop\Repo\Projects.git\trunk\KPIproduction\KPIWeb\KPIWeb\Account\Login.aspx.cs:строка 54KPIWeb.LogWriter  Void WriteError(System.Exception) Line Number: 0</message><properties><data name="log4net:HostName" value="HP_ProBook_4340" /></properties></event>
<event logger="KPIWeb.LogWriter" timestamp="2015-02-22T12:05:55.5269487+03:00" level="ERROR" thread="12" domain="/LM/W3SVC/6/ROOT-1-130690694922543297" username="HP_ProBook_4340\SiV@S"><message>System.Threading.ThreadAbortException: Поток находился в процессе прерывания.    в System.Threading.Thread.AbortInternal()    в System.Threading.Thread.Abort(Object stateInfo)    в System.Web.HttpResponse.AbortCurrentThread()    в System.Web.HttpResponse.End()    в System.Web.HttpResponse.Redirect(String url, Boolean endResponse, Boolean permanent)    в System.Web.HttpResponse.Redirect(String url)    в KPIWeb.Account.Login.LogIn(Object sender, EventArgs e) в c:\Users\SiV@S\Desktop\Repo\Projects.git\trunk\KPIproduction\KPIWeb\KPIWeb\Account\Login.aspx.cs:строка 54KPIWeb.LogWriter  Void WriteError(System.Exception) Line Number: 0</message><properties><data name="log4net:HostName" value="HP_ProBook_4340" /></properties></event>
<event logger="KPIWeb.LogWriter" timestamp="2015-02-22T12:09:13.2082554+03:00" level="ERROR" thread="9" domain="/LM/W3SVC/6/ROOT-1-130690697300499308" username="HP_ProBook_4340\SiV@S"><message>System.Threading.ThreadAbortException: Поток находился в процессе прерывания.    в System.Threading.Thread.AbortInternal()    в System.Threading.Thread.Abort(Object stateInfo)    в System.Web.HttpResponse.AbortCurrentThread()    в System.Web.HttpResponse.End()    в System.Web.HttpResponse.Redirect(String url, Boolean endResponse, Boolean permanent)    в System.Web.HttpResponse.Redirect(String url)    в KPIWeb.Account.Login.LogIn(Object sender, EventArgs e) в c:\Users\SiV@S\Desktop\Repo\Projects.git\trunk\KPIproduction\KPIWeb\KPIWeb\Account\Login.aspx.cs:строка 54KPIWeb.LogWriter  Void WriteError(System.Exception) Line Number: 0</message><properties><data name="log4net:HostName" value="HP_ProBook_4340" /></properties></event>
<event logger="KPIWeb.LogWriter" timestamp="2015-02-22T12:11:29.0960277+03:00" level="ERROR" thread="6" domain="/LM/W3SVC/6/ROOT-1-130690698608364114" username="HP_ProBook_4340\SiV@S"><message>System.Threading.ThreadAbortException: Поток находился в процессе прерывания.    в System.Threading.Thread.AbortInternal()    в System.Threading.Thread.Abort(Object stateInfo)    в System.Web.HttpResponse.AbortCurrentThread()    в System.Web.HttpResponse.End()    в System.Web.HttpResponse.Redirect(String url, Boolean endResponse, Boolean permanent)    в System.Web.HttpResponse.Redirect(String url)    в KPIWeb.Account.Login.LogIn(Object sender, EventArgs e) в c:\Users\SiV@S\Desktop\Repo\Projects.git\trunk\KPIproduction\KPIWeb\KPIWeb\Account\Login.aspx.cs:строка 54KPIWeb.LogWriter  Void WriteError(System.Exception) Line Number: 0</message><properties><data name="log4net:HostName" value="HP_ProBook_4340" /></properties></event>
<event logger="KPIWeb.LogWriter" timestamp="2015-02-22T12:12:45.5123985+03:00" level="ERROR" thread="10" domain="/LM/W3SVC/6/ROOT-1-130690699288843035" username="HP_ProBook_4340\SiV@S"><message>System.Threading.ThreadAbortException: Поток находился в процессе прерывания.    в System.Threading.Thread.AbortInternal()    в System.Threading.Thread.Abort(Object stateInfo)    в System.Web.HttpResponse.AbortCurrentThread()    в System.Web.HttpResponse.End()    в System.Web.HttpResponse.Redirect(String url, Boolean endResponse, Boolean permanent)    в System.Web.HttpResponse.Redirect(String url)    в KPIWeb.Account.Login.LogIn(Object sender, EventArgs e) в c:\Users\SiV@S\Desktop\Repo\Projects.git\trunk\KPIproduction\KPIWeb\KPIWeb\Account\Login.aspx.cs:строка 54KPIWeb.LogWriter  Void WriteError(System.Exception) Line Number: 0</message><properties><data name="log4net:HostName" value="HP_ProBook_4340" /></properties></event>
<event logger="KPIWeb.LogWriter" timestamp="2015-02-22T12:14:02.9658286+03:00" level="ERROR" thread="6" domain="/LM/W3SVC/6/ROOT-1-130690700079448255" username="HP_ProBook_4340\SiV@S"><message>System.Threading.ThreadAbortException: Поток находился в процессе прерывания.    в System.Threading.Thread.AbortInternal()    в System.Threading.Thread.Abort(Object stateInfo)    в System.Web.HttpResponse.AbortCurrentThread()    в System.Web.HttpResponse.End()    в System.Web.HttpResponse.Redirect(String url, Boolean endResponse, Boolean permanent)    в System.Web.HttpResponse.Redirect(String url)    в KPIWeb.Account.Login.LogIn(Object sender, EventArgs e) в c:\Users\SiV@S\Desktop\Repo\Projects.git\trunk\KPIproduction\KPIWeb\KPIWeb\Account\Login.aspx.cs:строка 54KPIWeb.LogWriter  Void WriteError(System.Exception) Line Number: 0</message><properties><data name="log4net:HostName" value="HP_ProBook_4340" /></properties></event>
<event logger="KPIWeb.LogWriter" timestamp="2015-02-22T12:15:50.6819896+03:00" level="ERROR" thread="5" domain="/LM/W3SVC/6/ROOT-1-130690701161710157" username="HP_ProBook_4340\SiV@S"><message>System.Threading.ThreadAbortException: Поток находился в процессе прерывания.    в System.Threading.Thread.AbortInternal()    в System.Threading.Thread.Abort(Object stateInfo)    в System.Web.HttpResponse.AbortCurrentThread()    в System.Web.HttpResponse.End()    в System.Web.HttpResponse.Redirect(String url, Boolean endResponse, Boolean permanent)    в System.Web.HttpResponse.Redirect(String url)    в KPIWeb.Account.Login.LogIn(Object sender, EventArgs e) в c:\Users\SiV@S\Desktop\Repo\Projects.git\trunk\KPIproduction\KPIWeb\KPIWeb\Account\Login.aspx.cs:строка 54KPIWeb.LogWriter  Void WriteError(System.Exception) Line Number: 0</message><properties><data name="log4net:HostName" value="HP_ProBook_4340" /></properties></event>
<event logger="KPIWeb.LogWriter" timestamp="2015-02-22T12:20:03.3994442+03:00" level="ERROR" thread="7" domain="/LM/W3SVC/6/ROOT-1-130690703795680811" username="HP_ProBook_4340\SiV@S"><message>System.Threading.ThreadAbortException: Поток находился в процессе прерывания.    в System.Threading.Thread.AbortInternal()    в System.Threading.Thread.Abort(Object stateInfo)    в System.Web.HttpResponse.AbortCurrentThread()    в System.Web.HttpResponse.End()    в System.Web.HttpResponse.Redirect(String url, Boolean endResponse, Boolean permanent)    в System.Web.HttpResponse.Redirect(String url)    в KPIWeb.Account.Login.LogIn(Object sender, EventArgs e) в c:\Users\SiV@S\Desktop\Repo\Projects.git\trunk\KPIproduction\KPIWeb\KPIWeb\Account\Login.aspx.cs:строка 54KPIWeb.LogWriter  Void WriteError(System.Exception) Line Number: 0</message><properties><data name="log4net:HostName" value="HP_ProBook_4340" /></properties></event>
<event logger="KPIWeb.LogWriter" timestamp="2015-02-22T12:21:42.8531326+03:00" level="ERROR" thread="6" domain="/LM/W3SVC/6/ROOT-1-130690704796488054" username="HP_ProBook_4340\SiV@S"><message>System.Threading.ThreadAbortException: Поток находился в процессе прерывания.    в System.Threading.Thread.AbortInternal()    в System.Threading.Thread.Abort(Object stateInfo)    в System.Web.HttpResponse.AbortCurrentThread()    в System.Web.HttpResponse.End()    в System.Web.HttpResponse.Redirect(String url, Boolean endResponse, Boolean permanent)    в System.Web.HttpResponse.Redirect(String url)    в KPIWeb.Account.Login.LogIn(Object sender, EventArgs e) в c:\Users\SiV@S\Desktop\Repo\Projects.git\trunk\KPIproduction\KPIWeb\KPIWeb\Account\Login.aspx.cs:строка 54KPIWeb.LogWriter  Void WriteError(System.Exception) Line Number: 0</message><properties><data name="log4net:HostName" value="HP_ProBook_4340" /></properties></event>
<event logger="KPIWeb.LogWriter" timestamp="2015-02-22T12:29:00.472163+03:00" level="ERROR" thread="5" domain="/LM/W3SVC/6/ROOT-1-130690709163087810" username="HP_ProBook_4340\SiV@S"><message>System.Threading.ThreadAbortException: Поток находился в процессе прерывания.    в System.Threading.Thread.AbortInternal()    в System.Threading.Thread.Abort(Object stateInfo)    в System.Web.HttpResponse.AbortCurrentThread()    в System.Web.HttpResponse.End()    в System.Web.HttpResponse.Redirect(String url, Boolean endResponse, Boolean permanent)    в System.Web.HttpResponse.Redirect(String url)    в KPIWeb.Account.Login.LogIn(Object sender, EventArgs e) в c:\Users\SiV@S\Desktop\Repo\Projects.git\trunk\KPIproduction\KPIWeb\KPIWeb\Account\Login.aspx.cs:строка 54KPIWeb.LogWriter  Void WriteError(System.Exception) Line Number: 0</message><properties><data name="log4net:HostName" value="HP_ProBook_4340" /></properties></event>
<event logger="KPIWeb.LogWriter" timestamp="2015-02-22T12:35:16.717683+03:00" level="ERROR" thread="9" domain="/LM/W3SVC/6/ROOT-1-130690712905251849" username="HP_ProBook_4340\SiV@S"><message>System.Threading.ThreadAbortException: Поток находился в процессе прерывания.    в System.Threading.Thread.AbortInternal()    в System.Threading.Thread.Abort(Object stateInfo)    в System.Web.HttpResponse.AbortCurrentThread()    в System.Web.HttpResponse.End()    в System.Web.HttpResponse.Redirect(String url, Boolean endResponse, Boolean permanent)    в System.Web.HttpResponse.Redirect(String url)    в KPIWeb.Account.Login.LogIn(Object sender, EventArgs e) в c:\Users\SiV@S\Desktop\Repo\Projects.git\trunk\KPIproduction\KPIWeb\KPIWeb\Account\Login.aspx.cs:строка 54KPIWeb.LogWriter  Void WriteError(System.Exception) Line Number: 0</message><properties><data name="log4net:HostName" value="HP_ProBook_4340" /></properties></event>
